Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - clang-analyzer-*
      - concurrency-*
      - google-*
      - linuxkernel-*
      - llvm-*
      - llvmlibc-*
      - misc-*
      - modernize-*
      - performance-*
      - readability-*
    Remove:
      - llvm-header-guard
      - google-readability-todo
      - google-readability-casting
      - readability-magic-numbers
      - readability-uppercase-literal-suffix
      - readability-implicit-bool-conversion
      - modernize-use-trailing-return-type
      - modernize-use-auto
      - modernize-use-using
      - modernize-deprecated-headers
      - llvmlibc-restrict-system-libc-headers
      - llvmlibc-callee-namespace
      - llvmlibc-implementation-in-namespace
      - concurrency-mt-unsafe
      - readability-identifier-length
      - bugprone-easily-swappable-parameters
      - misc-no-recursion
  UnusedIncludes: Strict
