local opts = { silent=true }
local set_keymap = vim.keymap.set
-- General
set_keymap({"n", "v"}, "<Space>", "<Nop>", opts)
-- Term
set_keymap("t", "<C-\\><C-\\>", "<C-\\><C-n>", opts)
-- Windows
set_keymap("n", "<C-h>", "<cmd>wincmd h<CR>", opts)
set_keymap("n", "<C-j>", "<cmd>wincmd j<CR>", opts)
set_keymap("n", "<C-k>", "<cmd>wincmd k<CR>", opts)
set_keymap("n", "<C-l>", "<cmd>wincmd l<CR>", opts)
set_keymap("n", "<C-Up>", "<cmd>wincmd +<CR>", opts)
set_keymap("n", "<C-Down>", "<cmd>wincmd -<CR>", opts)
set_keymap("n", "<C-Left>", "<cmd>wincmd <lt><CR>", opts)
set_keymap("n", "<C-Right>", "<cmd>wincmd ><CR>", opts)
set_keymap("n", "<C-q>", "<cmd>wincmd =<CR>", opts)
-- Tabs
set_keymap("n", "<C-n>", "<cmd>tabnew<cr>", opts)
set_keymap("n", "<C-x>", "<cmd>tabclose<cr>", opts)
-- NERDTree
set_keymap("n", "<C-b>", "<cmd>NERDTreeToggle<cr>", opts)
-- Telescope
set_keymap("n", "<space>ff", function() return require("telescope.builtin").find_files() end, opts)
set_keymap("n", "<space>fg", function() return require("telescope.builtin").live_grep() end, opts)
set_keymap("n", "<space>fb", function() return require("telescope.builtin").buffers() end, opts)
set_keymap("n", "<space>fh", function() return require("telescope.builtin").help_tags() end, opts)
-- LSP
set_keymap("n", "<space>e", vim.diagnostic.open_float, opts)
set_keymap("n", "[d", vim.diagnostic.goto_prev, opts)
set_keymap("n", "]d", vim.diagnostic.goto_next, opts)
set_keymap("n", "<space>q", vim.diagnostic.setloclist, opts)
set_keymap("n", "gD", vim.lsp.buf.declaration, opts)
set_keymap("n", "gd", vim.lsp.buf.definition, opts)
set_keymap("n", "K", vim.lsp.buf.hover, opts)
set_keymap("n", "gi", vim.lsp.buf.implementation, opts)
set_keymap("n", "gk", vim.lsp.buf.signature_help, opts)
set_keymap("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
set_keymap("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
set_keymap("n", "<space>wl", function() vim.inspect(vim.lsp.buf.list_workspace_folders()) end, opts)
set_keymap("n", "<space>D", vim.lsp.buf.type_definition, opts)
set_keymap("n", "<space>rn", vim.lsp.buf.rename, opts)
set_keymap("n", "<space>ca", vim.lsp.buf.code_action, opts)
set_keymap("n", "gr", vim.lsp.buf.references, opts)
set_keymap("n", "<space>f", vim.lsp.buf.formatting, opts)
set_keymap("n", "gh", "<cmd>ClangdSwitchSourceHeader<CR>", opts)
-- DAP
set_keymap("n", "<F5>", function() return require("dap").continue() end, opts)
set_keymap("n", "<F6>", function() return require("dap").step_over() end, opts)
set_keymap("n", "<F11>", function() return require("dap").step_into() end, opts)
set_keymap("n", "<F12>", function() return require("dap").step_out() end, opts)
set_keymap("n", "<space>b", function() return require("dap").toggle_breakpoint() end, opts)
set_keymap("n", "<space>B", function() require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: ")) end, opts)
set_keymap("n", "<space>lp", function() require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: ")) end, opts)
set_keymap("n", "<space>dr", function() require"dap".repl.toggle({}, "vsplit") end, opts)
set_keymap("n", "<space>dl", function() return require("dap").run_last() end, opts)
set_keymap("n", "<space>dc", function() return require("dap").terminate() end, opts)
set_keymap("n", "<space>di", function() return require("dap.ui.widgets").hover() end, opts)
set_keymap("n", "<space>d?", function()
                                local widgets=require("dap.ui.widgets")
                                widgets.centered_float(widgets.scopes)
                            end, opts)
-- Trouble
set_keymap("n", "<space>xx", "<cmd>Trouble<cr>", opts)
set_keymap("n", "<space>xw", "<cmd>Trouble workspace_diagnostics<cr>", opts)
set_keymap("n", "<space>xd", "<cmd>Trouble document_diagnostics<cr>", opts)
set_keymap("n", "<space>xl", "<cmd>Trouble loclist<cr>", opts)
set_keymap("n", "<space>xq", "<cmd>Trouble quickfix<cr>", opts)
set_keymap("n", "gR", "<cmd>Trouble lsp_references<cr>", opts)

